Fix actions/upload-artifact failure
Both gold and non-gold job were trying to perform the lockfile upload.

    With the provided path, there will be 1 file uploaded
    Artifact name is valid!
    Root directory input is valid!
    Error: Failed to CreateArtifact: Received non-retryable error:
    Failed request: (409) Conflict: an artifact with this name already exists on the workflow run