Fix distributed slice inside #[cortex_m_rt::entry] macro
Required because cortex-m-rt is stuck on an old version of syn.

    error: free static item without body
      --> tests/cortex/src/main.rs:36:5
       |
    36 |     static EMPTY: [i32];
       |     ^^^^^^^^^^^^^^^^^^^-
       |                        |
       |                        help: provide a definition for the static: `= <expr>;`

    error[E0277]: the size for values of type `[i32]` cannot be known at compilation time
      --> tests/cortex/src/main.rs:36:19
       |
    36 |     static EMPTY: [i32];
       |                   ^^^^^ doesn't have a size known at compile-time
       |
       = help: the trait `Sized` is not implemented for `[i32]`